# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: bundle-install
    init: |
      bundle install
      gp sync-done bundle-install
  - name: server-run
    command: |
      gp sync-await bundle-install
      sleep 10
      bundle exec ruby server.rb
  - name: preview
    command: gp preview $(gp url 8080)

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - port: 8080
#     onOpen: open-preview

