# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: bundle-install
    init: bundle install
  - name: server-run
    command: bundle exec ruby server.rb
  - name: frontend-run
    command: gp preview $(gp url 8080)

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 8080 for the frontend
    port: 8080
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
