# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: double ampersand
    command: echo 'Hello ' && echo 'World'

  - name: semicolon
    command: echo 'Hello '; echo 'World'

  - name: "&& fail"
    command: echox 'Hello ' && echo 'World'

  - name: "bash script"
    command: ./script.sh

  - name: "multiline"
    command: >
      echo 'Hello ' &&
      echo 'World'

  - name: "multiline 2"
    command: |
      echo 'Hello '
      echo 'World'
